### ISSUE TITLE
[BUG] window lacks scroll support

### ISSUE THREAD

**Issue by iwconfig** [timschneeb/GalaxyBudsClient#309]
**Describe the bug**  
I'm using a tiling window manager, and when the GalaxyBudsClient window is shrunken to a point where it cannot show all the content at once, the ability to scroll is not present.

**To Reproduce**  
Use a tiling wm or just shrink the window and try to scroll.

**Expected behavior**  
The ability to scroll the content and maybe, though not necessary, even show a scrollbar.

**Screenshots**  
![bild](https://user-images.githubusercontent.com/10843441/153737198-77cce46f-170f-4a98-932d-283feda94de0.png)

**Desktop (please complete the following information):**  
- Linux Debian 9 Stretch 
 - Application version: 4.4.0.0

**Comment by mickoz** [comment]
I installed the app today.  I go in advanced settings and it seems the last option is truncated, I don't know if there are more options I don't see because we can't scroll and it is fixed width. (I am in 4K and there might be scaling settings that influence, just saying in case you expect that screen to contain all element without the need of scrolling).  The window is not resizable either (I have not try any app to force this to test).

Here is a screenshot:

![image](https://github.com/ThePBone/GalaxyBudsClient/assets/6559557/05441656-b49f-4bc1-8731-68ab913a4ff6)

**Comment by ThePBone** [comment]
There aren't any other buttons below the 'earbud fit test'.

I'm currently in the process of rewriting the whole UI using the FluentAvalonia library, which will be resizable and much more responsive.

**Comment by timschneeb** [comment]
Fixed in the latest version: https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.0.0

**Comment by iwconfig** [comment]
Oh wow, it's really beautiful! And it works great. I like it! Thank you very much, you deserve a f-ing medal: 🥇 

*Really awesome!*
