### ISSUE TITLE
[REQ] Make "Resume/start playback if Buds are worn" work also for pause

### ISSUE THREAD

**Issue by fam4r** [timschneeb/GalaxyBudsClient#483]
Hello,

can you please make the functionality "Resume/start playback if Buds are worn" work also when the proximity sensor is going form covered to not covered (Wearing -> Idle, for at least one) - by sending a global "pause" state change (as per description : see picture that cites both play and pause)

![image](https://github.com/ThePBone/GalaxyBudsClient/assets/9888550/81e1372d-0afb-4f30-8f97-46eecc537baa)

Thank you

**Comment by sibwaze** [comment]
for me with my galaxy buds 2 pro, even auto resume doesn't work for some reason
I don't really know why and how to fix that

**Comment by fam4r** [comment]
Seems related / similar / duplicate of #365 (?)

**Comment by salihefee** [comment]
@timschneeb Is this normally supposed to work or is it not implemented altogether?

**Comment by timschneeb** [comment]
This isn't implemented because the earbuds themselves already send the pause signal when taking them off. (Or at least they are supposed to.) 
This behavior used to be always enabled with no way to turn it off, but newer Buds models actually have setting to disable/enable that. So maybe that's just turned off.

**Comment by salihefee** [comment]
It works on my phone but not on my linux laptop. I created a PR (#584) adding this as a setting in case you consider it for people who don't have it (like me and the person who created this issue :D)
