### ISSUE TITLE
[BUG] buds2 pro and "seamless connection"

### ISSUE THREAD

**Issue by wpzdm** [timschneeb/GalaxyBudsClient#498]
**Describe the bug**  
I can only connect the buds to another device after "forgetting" them on a previous device. The "seamless connection" seems not useful.

**To Reproduce**  
The "seamless connection" is enabled by default, so I think this is trivially reproducible. 

**Expected behavior**  
I can discover and connect to the buds when they are already connected to other devices?

**Desktop (please complete the following information):**  
macOS 13.0
 
 - Application version: 4.6

**Log files**  
[application.log](https://github.com/timschneeb/GalaxyBudsClient/files/15210287/application.log)

**Comment by onebone** [comment]
Samsung explains about the seamless connection that Buds will switch between devices that have "logged in to the same Samsung account". I don't see any option with Samsung account in the client so I think this issue is rather a feature request?

**Comment by timschneeb** [comment]
The "seamless connection" setting just flips a setting somewhere in the earbud's firmware. Because of that, I don't have any influence over its behavior.

The auto-switch feature, which is part of a seamless connection, requires a Samsung Account. I looked into reverse-engineering their private API; however, it is too complex and would require more work than it is worth.
